### ISSUE TITLE
ERROR [internal] load metadata for docker.io/twilio/twilio-cli:3.3.0

### ISSUE THREAD

**Issue by twilio-akiramoto** [Pham-dev/hls-blueprint-release#8]
Hello,
I am following the readme and getting this error when running the installer. 
 
What can I do to fix this?

`docker build --tag hls-ehr-installer --no-cache https://github.com/bochoi-twlo/hls-ehr.git#main
[+] Building 0.7s (2/2) FINISHED
 => CACHED [internal] load git source https://github.com/bochoi-twlo/hls-ehr.git#main                                                        0.0s
 => ERROR [internal] load metadata for docker.io/twilio/twilio-cli:3.3.0                                                                     0.7s
------
 > [internal] load metadata for docker.io/twilio/twilio-cli:3.3.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch anonymous token: unexpected status: 500 Internal Server Error`

**Comment by Pham-dev** [comment]
I just re-ran this step and passed for me.  Maybe try deleting the image and docker prune your setup and retry this step?
